#!/bin/bash
rekt="/usr/bin"
chmod +x *.sh
cp add-domain.sh $rekt/add-domain
cp add-trojan.sh $rekt/add-trojan
cp add-vless.sh $rekt/add-vless
cp add-vmess.sh $rekt/add-vmess
cp gboy.sh $rekt/gboy
cp menusys.sh $rekt/menusys
cp menutj.sh $rekt/menutj
cp menuvl.sh $rekt/menuvl
cp menuvm.sh $rekt/menuvm
cp renewtj.sh $rekt/renewtj
cp renewvl.sh $rekt/renewvl
cp renewvm.sh $rekt/renewvm
cp addtj.sh $rekt/addtj
cp addvl.sh $rekt/addvl
cp addvm.sh $rekt/addvm
cp deltj.sh $rekt/deltj
cp delvl.sh $rekt/delvl
cp delvm.sh $rekt/delvm
cp renewtj.sh $rekt/renewtj
cp renewvl.sh $rekt/rekt/renewvl
cp renewvm.sh $rekt/renewvm
cp xp.sh $rekt/xp
cp clear-log.sh $rekt/clear-log
cp cek-service.sh $rekt/cek-service
cp cert.sh $rekt/cert
cp speedtest.sh $rekt/speedtest
cp clear-ram.sh $rekt/clear-ram
cp cektj.sh $rekt/cektj
cp cekvm.sh $rekt/cekvm
cp cekvl.sh $rekt/cekvl
cp backup.sh $rekt/backup
cp restart.sh $rekt/restart
cp delexp.sh $rekt/delexp
